# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
test:
  servers: "127.0.0.1:9160"
  keyspace: "quorumer_test"
  thrift:
    timeout: 3
    retries: 2

development:
  servers: "127.0.0.1:9160"
  keyspace: "quorumer_development"
  thrift:
    timeout: 3
    retries: 2